remove version-check.sh from process

diff --git a/src/01_lfs/01_prepare/checkup b/src/01_lfs/01_prepare/checkup
--- a/src/01_lfs/01_prepare/checkup
+++ b/src/01_lfs/01_prepare/checkup
@@ -3,7 +3,7 @@
 function	checkup()
 {
 	# Install dependencies
-	apk add --update \
+	/sbin/apk add --update \
 		vim \
 		binutils \
 		bison \
@@ -18,13 +18,13 @@ function	checkup()
 	pinfo "Symlink /bin/sh to /bin/bash"
 	[ /bin/sh -ef /bin/bash ] || (_rm /bin/sh; _ln -s /bin/bash /bin/sh)
 
-	# Check if all good
-	pinfo "Check all good with LFS script"
+	# # Check if all good
+	# pinfo "Check all good with LFS script"
 
-	if bash "${DIR_SCRIPT}/version-check.sh"; then
-		ppass "version-check.sh pass"
-	else
-		pfail "Error: version-check.sh failed"
-		exit 1
-	fi
+	# if bash "${DIR_SCRIPT}/version-check.sh"; then
+	# 	ppass "version-check.sh pass"
+	# else
+	# 	pfail "Error: version-check.sh failed"
+	# 	exit 1
+	# fi
 }
